[versions]
# Plugins
androidGradlePlugin = "9.3.1"
kotlinGradlePlugin = "2.4.10"
ksp = "2.3.11"
composeMultiplatform = "1.11.1"
composeIcons = "1.7.3"

# AndroidX & Compose
activity = "1.13.0"
composeMaterial3 = "1.11.0-alpha07"
lifecycle = "2.11.0"
navigationCompose = "2.9.8"
uiText = "1.11.4"
room = "2.8.4"
work = "2.11.2"
preference = "2.2.0"

# Scraping & Network
jsoup = "1.18.1"
nicehttp = "0.4.18"
coil = "3.5.0"

# Utils
kotlinxCollectionsImmutable = "0.5.1"
kotlinxIoCore = "0.9.1"
markwon = "4.6.2"
fuzzywuzzy = "1.4.0"
mlkitTranslate = "17.0.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
logger = "2.2.0"

[libraries]
# AndroidX & Lifecycle
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# Compose Multiplatform / UI
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "composeIcons" }
compose-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeIcons" }
compose-resources  = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }

# Room (Persistence)
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Scraping & Network
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
nicehttp = { group = "com.github.Blatzar", name = "NiceHttp", version.ref = "nicehttp" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Notes & Content
markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
markwon-html = { group = "io.noties.markwon", name = "html", version.ref = "markwon" }
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
compose-preference = { module = "me.zhanghai.compose.preference:preference", version.ref = "preference" }
mlkit-translate = { group = "com.google.mlkit", name = "translate", version.ref = "mlkitTranslate" }

# Utils
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
logger = { group = "com.orhanobut", name = "logger", version.ref = "logger"}

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
